# !! File must end with empty line !!
dependencies:
  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: jx-spring-boot-demo
  repository: file://../jx-spring-boot-demo
